endpoints = {
		'category': ('api_key', 'file_type', 'category_id'),
		'category/children': ('api_key', 'file_type', 'category_id', 'realtime_start', 'realtime_end'),
		'category/related': ('api_key', 'file_type', 'category_id', 'realtime_start', 'realtime_end'),
		'category/series': ('api_key', 'file_type', 'category_id', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order', 'filter_variable', 'filter_value', 'tag_names', 'exclude_tag_names'),
		'category/tags': ('api_key', 'file_type', 'category_id', 'realtime_start', 'realtime_end', 'tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'category/related_tags': ('api_key', 'file_type', 'category_id', 'realtime_start', 'realtime_end', 'tag_names', 'exclude_tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'releases': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order'),
		'releases/dates': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order', 'include_release_dates_with_no_data'),
		'release': ('api_key', 'file_type', 'release_id', 'realtime_start', 'realtime_end'),
		'release/dates': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order', 'include_release_dates_with_no_data'),
		'release/series': ('api_key', 'file_type', 'release_id', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order', 'filter_variable', 'filter_value', 'tag_names', 'exclude_tag_names'),
		'release/sources': ('api_key', 'file_type', 'release_id', 'realtime_start', 'realtime_end'),
		'release/tags': ('api_key', 'file_type', 'release_id', 'realtime_start', 'realtime_end', 'tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'release/related_tags': ('api_key', 'file_type', 'release_id', 'realtime_start', 'realtime_end', 'tag_names', 'exclude_tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'release/tables': ('api_key', 'file_type', 'release_id', 'element_id', 'include_observation_values', 'observation_date'),
		'series': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end'),
		'series/categories': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end'),
		'series/observations': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end', 'limit', 'offset', 'sort_order', 'observation_start', 'observation_end', 'units', 'frequency', 'aggregation_method', 'output_type', 'vintage_dates'),
		'series/release': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end'),
		'series/search': ('api_key', 'file_type', 'search_text', 'search_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order', 'filter_variable', 'filter_value', 'tag_names', 'exclude_tag_names'),
		'series/search/tags': ('api_key', 'file_type', 'series_search_text', 'realtime_start', 'realtime_end', 'tag_names', 'tag_group_id', 'tag_search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'series/search/related_tags': ('api_key', 'file_type', 'series_search_text', 'realtime_start', 'realtime_end', 'tag_names', 'exclude_tag_names', 'tag_group_id', 'tag_search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'series/tags': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end', 'order_by', 'sort_order'),
		'series/updates': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'filter_value', 'start_time', 'end_time'),
		'series/vintagedates': ('api_key', 'file_type', 'series_id', 'realtime_start', 'realtime_end', 'limit', 'offset', 'sort_order'),
		'sources': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order'),
		'source': ('api_key', 'file_type', 'source_id', 'realtime_start', 'realtime_end'),
		'source/releases': ('api_key', 'file_type', 'source_id', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order'),
		'tags': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'related_tags': ('api_key', 'file_type', 'realtime_start', 'realtime_end', 'tag_names', 'exclude_tag_names', 'tag_group_id', 'search_text', 'limit', 'offset', 'order_by', 'sort_order'),
		'tags/series': ('api_key', 'file_type', 'tag_names', 'exclude_tag_names', 'realtime_start', 'realtime_end', 'limit', 'offset', 'order_by', 'sort_order')
}
